### ISSUE TITLE
Supports JSON, TSV and CSV Format

### ISSUE THREAD

**Issue by CouteauFourchette** [CouteauFourchette/chartshare#2]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [ ] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by mladenoff** [comment]
When I upload a CSV and then go back to "my datasets" (as demo user) if I click the link to the new dataset it tries to send me to '#/datasets/undefined'. Is it not getting its ID back from the backend when it saves?

**Comment by CouteauFourchette** [comment]
I made a change in the way I merge the datasets (which is now showing both the new dataset and the dataset saved. If you click on the new one, it doesn't have an ID. It will be corrected soon.

**Comment by CouteauFourchette** [comment]
This should be fixed now

**Comment by mladenoff** [comment]
lgtm
